[package]
name = "fractal_dimension_async"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24" # For image processing
tokio = { version = "1", features = ["full"] } # For async programming
futures = "0.3" # For async utilities

